fix metadata
UniversalMediaServer/UniversalMediaServer pull request #3648
Opened 2022-11-23 15:23 UTC by SurfaceS

DLNAMediaVideoMetadata -> refactored to MediaVideoMetadata (not dlna related)

**MediaTableAudiotracks, MediaTableChapters, MediaTableSubtracks**
- give data themself (not from the MediaTableFiles).

**MediaVideoMetadata**
- now contain everything under it (api data as well).
- direct update MediaTableVideoMetadata

**TvSerieMetadata**
- created class with api data.
- direct update MediaTableTVSeries

**APIUtils**
- fix country is string with comma not array
- set api url static final
- fully set MediaVideoMetadata
- fully set TvSerieMetadata

**React player** 
- fix logo and poster
- added Rated to reflect old interface
- added Year Started to reflect old interface
- added Total Seasons to reflect old interface
- added IMDB link to reflect old interface

about #3575, after some requests, it's appear the API server does not give these data.

2022-11-26 16:08 UTC, SurfaceS commented
@SubJunk It is a reason that UMS does not store `PLOT`, `TAGLINE` and `VOTES` for `MediaTableVideoMetadata`?

2022-11-26 21:40 UTC, SubJunk commented
@SurfaceS they were there in the past, I don't know how they got removed. Sounds like an accident. That reminds me it would be good to set up regression tests for the web interface, maybe that can be the next thing I work on

2022-11-26 22:53 UTC, SurfaceS commented
@SubJunk added them back then.

2022-12-03 02:10 UTC, SubJunk commented
This looks great, thanks

2022-12-03 02:27 UTC, SubJunk commented
@SurfaceS this looks good but it doesn't build, I get a NSIS error:

```
[INFO] ------------------------------------------------------------------------
[INFO] [MAKENSIS]  - BgImage::Destroy
[INFO] BUILD FAILURE
[INFO] [MAKENSIS]  - BgImage::Redraw
[INFO] ------------------------------------------------------------------------
[INFO] [MAKENSIS]  - BgImage::SetBg
[INFO] Total time:  01:43 min
[INFO] [MAKENSIS]  - BgImage::SetReturn
[INFO] Finished at: 2022-12-03T15:20:33+13:00
[INFO] [MAKENSIS]  - BgImage::Sound
[INFO] ------------------------------------------------------------------------
[INFO] [MAKENSIS]  - Dialer::AttemptConnect
[ERROR] Failed to execute goal org.codehaus.mojo:nsis-maven-plugin:1.0-SNAPSHOT:compile (build-ums-windows) on project ums: Execution of makensis compiler failed. See output above for details. -> [Help 1]
[INFO] [MAKENSIS]  - Dialer::AutodialHangup
[ERROR]
[INFO] [MAKENSIS]  - Dialer::AutodialOnline
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [MAKENSIS]  - Dialer::AutodialUnattended
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [MAKENSIS]  - Dialer::GetConnectedState
[ERROR]
[INFO] [MAKENSIS]  - InstallOptions::dialog
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [MAKENSIS]  - InstallOptions::initDialog
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] [MAKENSIS]  - InstallOptions::show
[INFO] [MAKENSIS]  - LangDLL::LangDialog
[INFO] [MAKENSIS]  - LockedList::AddApplications
[INFO] [MAKENSIS]  - LockedList::AddCaption
[INFO] [MAKENSIS]  - LockedList::AddClass[INFO] [MAKENSIS]  - LockedList::AddClass
[INFO] [MAKENSIS]  - LockedList::AddCustom
[←[1;34mINFO←[m] [MAKENSIS]  - LockedList::AddFile
[←[1;34mINFO←[m] [MAKENSIS]  - LockedList::AddFolder
[←[1;34mINFO←[m] [MAKENSIS]  - LockedList::AddModuleA duplicate file name exists, or the file
cannot be found.
```

2022-12-03 03:38 UTC, SubJunk requested changes
I can't see any bugs, just a couple of language fixes

2022-12-03 03:38 UTC, SubJunk commented on src/main/java/net/pms/database/MediaTableTVSeries.java
> +	public static void updateAPIMetadata(final Connection connection, final TvSerieMetadata serieMetadata, final Long tvSeriesId) {
Should be `series` not `serie` (the s does not mean plural in this case, because English language is silly...)

2022-12-03 03:38 UTC, SubJunk commented on src/main/java/net/pms/media/metadata/ApiProdutionCompany.java
> +public class ApiProdutionCompany {
Should be `production` not `prodution`

2022-12-06 23:40 UTC, SubJunk approved these changes

2022-12-06 23:40 UTC, merged